UKHomeOffice/sgmr-service

- README.md
- env.yaml
Update README with corrected service name
> CG-72 Remove redundant ECR AWS credentials

- .drone.yml
- .eslintrc.js
- README.md
- package-lock.json
- package.json
- webpack.config.js
> Add linter

- src/components/Header.jsx
- src/components/Nav.jsx
Navigation is clickable and behaves as expected
EXCEPT it remains in html focus state until you click elsewhere, whereas it should remove focus on upclick or keyup -- noted to investigate further
> Add active navigation

- src/components/SectionTable.jsx
- src/components/contentArray.js
A lot of code in here that will be replaced with nicer code once API is connected
> Cg84 people page

- src/components/Forms/UserRegister.jsx
Just adding mobile number field
Working on new branch for 2FA
> Add mobileNumber to register form

- src/components/Forms/FormPeople.jsx
- src/components/Forms/FormVessels.jsx
- src/components/Forms/SignIn.jsx
- src/components/Forms/UserInputCode.jsx
- src/components/Forms/UserRegister.jsx
- src/components/Forms/UserResendCode.jsx
- src/components/Main.jsx
- src/sass/main.scss
- webpack.config.js
> Cg 127 twofa

- package-lock.json
- package.json
- src/components/Forms/CreatePerson.jsx
- src/components/Forms/FormPeople.jsx
- src/components/Forms/UserInputCode.jsx
- src/components/Forms/UserResendCode.jsx
> Cg 103 people form

- src/components/Forms/EditAccount.jsx
- src/components/Forms/FormPeople.jsx
- src/components/Forms/FormVessels.jsx
- src/components/Forms/FormVoyagePeople.jsx
- src/components/Forms/FormVoyageVessel.jsx
- src/components/Forms/SignIn.jsx
- src/components/PageAccount.jsx
- src/components/SectionTable.jsx
- src/components/SectionTabs.jsx
NOTE: /people does not yet redirect, will come back to this as needs doing in redux code
> Cg 125 token validity

- kube/deployment.yml
Corrects the user id from 1000 to 100
> Correct the user id in nginx deployment

- kube/deployment.yml
Remove the liveness and readiness checks (as they don't exist)
> Remove probes from deployment

- kube/deployment.yml
Various changes required to correct the deployment
> Rewrite the kube deployment

- src/components/SectionTable.jsx
We don't have edit functionality atm, so lets disable this.
> Disable link

- .babelrc
- package-lock.json
- package.json
- src/index.jsx
- src/lib/polyfills.js
> Browser support

- src/components/Forms/FormPeople.jsx
- src/components/Forms/FormVoyageCheckDetails.jsx
- src/components/Forms/FormVoyageSubmitted.jsx
- src/components/Forms/UserRegister.jsx
- src/components/PageAccount.jsx
- src/components/PageContainer.jsx
- src/components/SectionTable.jsx
**Catch 400 error**
> if you have not created a person before you will need to create a person before following these steps
- go to _people_
- go to _save a person_
- attempt to save a person with a _document type_ and _document number_ you have used before
- you should see a page level error of 'This person already exists' 
You will need to scroll to the top yourself to see this as the scrollToTopOnError has not been rolled across all forms yet
**Clear account page data & people/vessel form data when leave page**
- make sure devtools is open
- go to _vessel_
- click on a _vessel name_ to edit it
- make some changes to the form and submit it
- check localStorage, there should be no `formData` or `data` in there
- do the same for 
- - _people_ / _person name_
- - _vessel_ / _save a vessel_ …
> Small fixes

- src/components/Forms/validationRules.js
- src/components/People/CreateAPerson.jsx
- src/components/People/FormPerson.jsx
- src/utils/date.js
**Testing**
- go to _People_
- go to _Save a person_
----
**Required fields**
1. submit the form without entering any data
> every field should display an error message as currently all fields are required
----
**Date of birth dates must be valid**
Enter data into all fields other than date fields so they no longer error.
Then enter the following into date of birth day/month/year
> These scenarios should result in an error  (day, month, year)
- g, 10, 2001
- 01, 10,
- 01, 55, 2001
- 01, 10, 1800
- 01, 10, 2023
> This scenario should pass
- 01, 10, 2001
----
**Expiry dates must be valid**
Enter data into all fields other than date fields so they no longer error.
Then enter the following into Expiry date day/month/year
> These scenarios should result in an error  (day, month, year)
- g, 10, …
> Cg 202 person validation

- src/components/People/CreateAPerson.jsx
- src/components/People/EditPerson.jsx
- src/utils/date.js
**To test**
- go to _people_
- click on a _person name_
> You should see the fields populated based on what you entered at creation
> NOTE: if you created a person in the past it may not have saved their date of birth or document expiry, this has been fixed now
----
**Changing no fields**
- click 'Add to saved people list' without changing any fields
> You should be returned to /people
----
**Not saving changes**
- edit a field
- click _Exit without saving'
> You should be returned to /people without those changes being saved
----
**Editing date fields**
**Date of birth dates must be valid**
Enter data into all fields other than date fields so they no longer error.
Then enter the following into date of birth day/month/year
> These scenarios should result in an error  (day, month, year)
- …
> Cg 202 edit person validation

- src/components/Forms/EditVoyage.jsx
- src/components/Forms/FormVoyage.jsx
- src/components/Forms/FormVoyageCheckDetails.jsx
- src/components/Forms/FormVoyagePeople.jsx
- src/components/Forms/FormVoyageVessel.jsx
- src/components/Main.jsx
- src/components/SectionTabs.jsx
- src/components/Vessel/FormVessel.jsx
- src/constants/ClientConstants.js
- src/state/voyage.js
**TESTING**
- go to _reports_
- _save a voyage_
- you must include a _vessel name_
- I recommend including a few/all fields on every page
**You can click a voyage and see the check info page**
- click on a _vessel name_
> you should see the 'Check all information' page with your data filled in
----
**You can edit any section**
- click on _change_ for a section
- you should see the form for that section with your answers prepopulated
- change an answer and complete the form
> you should see your edited answer on the _check information_ page
Repeat this for each section
- departure details
- arrival details
- vessel
- people
- responsible person
----
**Special cases to test**
**Vessel Selection**
- add a vessel to your voyage by ticking the checkbox 
- complete the voyage …
> Create EditVoyage page

- package-lock.json
- package.json
- src/components/Forms/FormVoyageConfirm.jsx
- src/components/SectionTabs.jsx
- src/sass/main.scss
TO TEST
**Cancelling a newly created report**
- go to save a new report
- fill out the form, you need to enter at least a vessel name
- complete the form to the 'check details' page
> scroll down the page and you should see a 'cancel' button
- click cancel
> you should be taken to the /reports page
> you should be able to see that report in the 'cancelled' tab
----
**Cancelling an older draft report**
- go to save a new report
- fill out the form, you need to enter at least a vessel name
- click on your vessel name
> you should be taken to the 'check details' page
> scroll down the page and you should see a 'cancel' button
- click cancel
> you should be taken to the /reports page
> you should be able to see that report in the 'cancelled' …
> Cg 132 cancel voyage

- src/components/Forms/validationRules.js
- src/components/Main.jsx
- src/components/SectionTable.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormDataFormatting.js
- src/components/Voyage/VoyageFormValidation.js
- src/utils/apiHooks.js
NOTES
- branched from master so does not have the new people functionality
- refactoring save voyage form to handle validation and editing
- this PR sets up the structure and handles page-1 only
- attempting to edit an existing voyage will break as the location has been temporarily removed while recreating the flow
- departure time is temporarily removed to reduce number of new things (formatting/validating) in this PR and will be re-added with validation in the next one
----
**TO TEST**
- start a new voyage
- fill in some or all departure details
> If you have not entered departure date in a valid date format you should see a field level error
> If you have entered the date in a valid format you should see a blank page 2
- you can view the saved voyage details either in …
> Cg 121 setup departure page

- src/components/Forms/validationRules.js
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormDataFormatting.js
- src/components/Voyage/VoyageFormValidation.js
- src/utils/time.js
TO TEST
- save a new voyage
**Form should allow submit with null time fields**
- enter a date (and any other fields) but NO time
- click save and continue
> You should see page 2 (which is blank) and be able to see in Network tab that the PATCH was successful
**Form should not allow invalid time fields**
- go back to page 1
- enter an invalid hour (eg 33)
- click save and continue
> you should see a field level error
- enter an invalid minute (eg 77)
- click save and continue
> you should see a field level error
- enter an invalid hour ('dd')
- click save and continue
- you should see a field level error
- enter an invalid minute ('dd')
- click save and continue
- you should see a field level error
**Valid times should allow submit**
- enter a valid time (eg 12:20, 3:05; …
> Cg 121 add time field

- package-lock.json
- src/components/PageIntro.jsx
- src/components/SectionTabs.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormDataFormatting.js
- src/components/Voyage/VoyageFormValidation.js
- src/utils/apiHooks.js
- src/utils/date.js
- src/utils/time.js
TO TEST
- if you have none, create a report
- click on the link on the date
> you should see the check details page
> this page should show the saved details of your voyage (for newer voyages this will only be the departure details
----
**I can edit a voyage**
- click 'Change' next to departure details
> you should be taken to the departure details page with your voyage details prepopulated
- change something (add/remove/edit)
- click save and continue
> you should see a blank page 2
- go back to /reports
- click on your voyage
> you should see the check details page with your changes
----
NOTES
- page 2-5 not yet available
- arrivalDate will show Invalid Date on check page as it is not yet handled in this voyage
> Cg 121 check page and edit

- package-lock.json
- src/components/Forms/validationRules.js
- src/components/SectionTable.jsx
- src/components/Vessel/CreateAVessel.jsx
- src/components/Vessel/FormVessel.jsx
- src/components/Vessel/VesselTable.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/FormVessels.jsx
- src/components/Voyage/FormVoyageVessels.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormDataFormatting.js
- src/components/Voyage/VoyageFormValidation.js
- src/sass/main.scss
NOTES : have added an error for missing voyageId scenario, need to discuss with Andrew/TomC to agree what this should be and update it
TO TEST
- Go to /vessels
- Go to save a vessel
- Fill out the fields (most are optional) and click save
- Make sure you have at least 2 saved vessels before continuing
**I can see my saved vessels on the voyage form**
- Go to /reports
- Go to start now
- Complete the departure page (only date is required)
- Click save and continue
- Complete the arrival page (nothing is required)
- Click save and continue
> you should see a list of your saved vessels as well as a vessel form
**I can select only one vessel at a time**
- Tick one checkbox
- Tick the other checkbox
> you should see them behave as though they’re radio buttons and you can only select one at …
> Cg 121 vessel page

- package-lock.json
- src/components/PageContainer.jsx
- src/components/People/CreateAPerson.jsx
- src/components/People/EditPerson.jsx
- src/components/People/FormPerson.jsx
- src/components/People/PeopleFormDataFormatting.jsx
- src/components/SectionTable.jsx
- src/components/SectionTablePeople.jsx
- src/components/SectionTableVessels.jsx
- src/components/SectionTabs.jsx
- src/components/User/UserInputCode.jsx
- src/components/Vessel/CreateAVessel.jsx
- src/components/Vessel/EditVessel.jsx
- src/components/Vessel/FormVessel.jsx
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/FormVoyagePeople.jsx
- src/components/Voyage/FormVoyageVessels.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormDataFormatting.js
- src/components/contentArray.js
- src/lib/SecureRoute.jsx
- src/utils/apiHooks.js
TO TEST
Recommend 
-  clear cache/cookies
- `rm -rf node_modules package-lock.json`
- `npm i && npm run build-dev && npm start`
——
**You should be forced to sign in if you do not have a valid token**
NAV:
- Sign in
- Delete your token
- Click on a menu link (vessels, people, account)
- > you should be taken to the sign in page
- Sign in
- > you should be taken to the page of the menu link you clicked on
- Go to /reports
- Start a new report
- Go to page 2 (arrivals)
- Delete your token
- Click on save and continue
- > you should be taken to the sign in page
- Sign in
- > you should be taken back to page 2 (arrivals)
- Click back
- > you should be taken to /reports (rather than /verify)
- Go to /vessels
- Go to save a vessel
- Delete your token
- Click exit without saving
- > you should be …
> Cg 196 handle signin redirect

- package-lock.json
- src/components/People/FormPerson.jsx
- src/components/Voyage/FormVoyagePeople.jsx
- src/components/Voyage/FormVoyageVessels.jsx
- src/components/Voyage/PeopleManifest.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormDataFormatting.js
ADD SAVED PEOPLE TO MANIFEST
- Add checkboxes to voyage people list
- On add to voyage all checked people are added
TEST
- Check some people
- People shown on manifest on voyage people page and check page
- People count reflects total people on manifest
NOTE: when you click 'add button' the manifest component does not refresh, I will come back to this after doing error handling
> Cg 121 add saved person

- src/components/Forms/validationRules.js
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormValidation.js
- src/utils/date.js
- src/utils/time.js
VOYAGE FOLLOWS STANDARD VALIDATION RULES
TEST
- Departure date is valid format 
- Departure time is valid format
- Departure date + time is in future
- Arrival date is valid format
- Arrival time is valid format
- Arrival date + time is in future
On attempt to submit voyage report the following exist
- vesselName
- registration
- departureDate
- departureTime
- departurePort
- arrivalDate
- arrivalTime
- arrivalPort
Note: people validation not in this PR
submit to 'Presubmitted' state not in this PR
> Cg 121 validation

- src/components/Vessel/EditVessel.jsx
- src/components/Vessel/VesselDataFormatting.jsx
Bug fix - when editing a vessel it wasn't saving all the changes
> Update edit vessel to handle portOfRegistry and field changes correctly

- src/components/SectionTabs.jsx
- src/utils/apiHooks.js
TO TEST
- click on start report
- go back to /reports
> you should not see any Invalid Date reports
> Delete invalid reports

- src/components/People/FormPerson.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormValidation.js
TEST
On the voyage people form:
- Error shown if any mandatory fields are missing
- Error shown if date format is invalid
- Error shown if date of birth is after today
- Error shown if document expiry is before today
- When no errors, form is submitted and person 
> Saved to voyage and visible on manifest
On the people & edit person forms:
as above, but
> Saved to people and visible on /people
> Add person validation

- package-lock.json
- package.json
- src/components/People/FormPerson.jsx
AC: add `Passenger` as a `personType` option
TO TEST:
**Create new person**
- go to **People**
- select `Passenger` as the type
- save person
- you should be returned to /people with that person listed with a people type of Passenger
**Add person to voyage report**
- go to **Reports**
- create a new report
- on the `People` section create a new person
- select `Passenger` as the type
- save person
- you should be returned to the voyage report with that person now listed on the manifest with the people type of Passenger
> Add passenger

- .github/pull_request_template.md
Add a developer pull request template/checklist to help with the pull request review.
> COP-2229: Add pull request template

- src/components/User/SignIn.jsx
Fixes bug where user cannot sign in due to expired token not being cleared from local storage.
\* Required
> COP-1179: sGMR User fails to login

- src/components/Forms/FormVoyageSubmitted.jsx
- src/components/People/FormPerson.jsx
- src/components/User/SignIn.jsx
- src/components/User/UserInputCode.jsx
- src/components/User/UserRegister.jsx
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/FormResponsiblePerson.jsx
- src/components/Voyage/PeopleManifest.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormValidation.js
This branch makes content and layout changes to SGMR as outlined by content design audit (see presentation and comments on ticket for full description: https://support.cop.homeoffice.gov.uk/browse/COP-2279)
- Pull the branch and run locally. Clone sgmr-data-api and also run locally. 
1. Sign In page: 
- Navigate to http://localhost:8080/sign-in 
- You should see the "Create account" title and link is now on the right hand side of the Sign in section, rather than below. 
- Also should see a link below Sign In button to "Problems signing in?" (placeholder as currently doesn't lead anywhere - to be added).
2. Register page:
- navigate to http://localhost:8080/register
- Text changes and should see a new link: "Help choosing a valid password" (also doesn't lead anywhere now - to be added.)
3. …
> COP-2279: Make content changes to sGMR based on content design audit

- index.html
- package.json
Adds a Matomo tracking code in the head of the service. Also changes the dev build script from "build-dev" to "build:dev" in package.json for consistency. 
- Pull branch and run locally. 
- Navigate to  http://localhost:8080/. Inspect the code and will see the Matomo tracking code in the head of app. 
\* Required
> COP-2261: Add the Matomo tracking code to sGMR

- package-lock.json
- package.json
- src/components/Main.jsx
- src/components/PageAccount.jsx
- src/components/PageContainer.jsx
- src/components/User/EditAccount.jsx
- src/components/User/__tests__/EditAccount.test.jsx
- src/components/UserContext.jsx
- src/components/__tests__/PageAccount.test.jsx
This branch enables a user to edit their details. It adds "Context" to the app to set the user object in a global store so these details can be passed more easily though the component tree. Prior to these changes, there was no link to the EditAccount page in the app and the user details were being passed via local storage. After these changes, "UserContext" is set when the user logins into the homepage and is accessed within the other components. When the user makes a change, a PATCH request is sent to the API which feeds back to the Account page. 
- Pull the branch and run locally. Clone sgmr-data-api and also run locally.
- register and sign in via: http://localhost:8080/register
- Navigate to the Account page via the Nav Bar or via: http://localhost:8080/account
- The User details …
> COP-2494: Enable a user to edit their user profile

- src/components/Forms/validationRules.js
- src/components/Voyage/FormError.jsx
- src/components/Voyage/FormResponsiblePerson.jsx
- src/components/Voyage/VoyageFormValidation.js
- src/components/Voyage/__tests__/FormResponsiblePerson.test.jsx
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
- src/setupTests.js
Make most the fields mandatory on the responsible person form.
1. Click `Start new` to report a new voyage
2. Proceed to `Add the skipper's address (5)` step of the form - http://localhost:8080/save-voyage/page-5
3. Click `Save and continue` without filling any user's details
4. You should see validation errors for the mandatory fields
\* Required
> COP-2117: Validation of responsible person

- src/components/Footer.jsx
- src/components/Help.jsx
- src/components/Main.jsx
- src/lib/config.js
- src/sass/main.scss
This branch adds a "Help" page for the service as outlined in: https://support.cop.homeoffice.gov.uk/browse/COP-2507. It adds a link to this page in the Footer.
- Run the service locally, and navigate to: http://localhost:8080/help, or click on the "Help" link in the footer.
- You should see the content as defined in the ticket above.
\* Required
> COP-2511: Build the help page

- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/FormResponsiblePerson.jsx
- src/components/Voyage/FormVoyagePeople.jsx
- src/components/Voyage/FormVoyageVessels.jsx
- src/components/Voyage/PeopleManifest.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormDataFormatting.js
- src/components/Voyage/VoyageFormValidation.js
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
- src/constants/ApiConstants.js
- src/constants/ClientConstants.js
Replace magic string with constants for voyage statuses and form steps.
Just a refactoring, everything should work as before.
\* Required
> Refactor magic strings for voyage statuses and form steps

- .gitignore
- cypress/fixtures/user-registration.json
- cypress/fixtures/users.json
- cypress/integration/sGMR/add-people.spec.js
- cypress/integration/sGMR/add-vessel.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/my-account.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/plugins/index.js
- cypress/scripts/check-user-exist.sh
- cypress/scripts/delete-reports.sh
- cypress/support/commands.js
- cypress/support/utils.js
This Pull Request has end to end tests reports,
Add, cancel & save voyage report.
generated reports deleted after all the tests completed.
npm run cypress:test -- --spec cypress/integration/sGMR/add-voyage-report.spec.js
\* Required
> COP-2896: Add E2E tests for adding voyage report

- cypress/fixtures/user-registration.json
- cypress/fixtures/users.json
- cypress/integration/sGMR/add-people.spec.js
- cypress/integration/sGMR/add-vessel.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/my-account.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/scripts/check-user-exist.sh
- cypress/support/commands.js
- package-lock.json
- package.json
Refactor user registration and login commands to make them faster.
\* Required
> Refactor user login and registration in e2e tests

- cypress/integration/sGMR/account-deletion.spec.js
- src/components/Main.jsx
- src/components/Nav.jsx
- src/components/User/DeleteAccount.jsx
- src/components/User/DeleteConfirmation.jsx
- src/components/User/EditAccount.jsx
- src/components/User/__tests__/EditAccount.test.jsx
- src/lib/Auth.js
Add a new functionality allowing users to completely delete their account.
1. Sign in
2. Go to the `Account` page
3. Click `Edit Account`
4. Click `Delete this account`
5. Confirm by choosing `Yes`
6. Press `Continue`
7. You should see a confirmation page and your account will now be deleted
\* Required
> COP-2132: Add account deletion functionality

- src/components/People/CreateAPerson.jsx
- src/components/People/EditPerson.jsx
- src/components/People/FormPerson.jsx
- src/components/User/UserInputCode.jsx
- src/components/User/UserRegister.jsx
- src/components/Vessel/CreateAVessel.jsx
- src/components/Vessel/EditVessel.jsx
- src/components/Vessel/FormVessel.jsx
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/VoyageFormContainer.jsx
Refactor form errors to use a common `FormError` component to reduce code duplication.
\* Required
> Refactor form errors

- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- cypress/plugins/index.js
- cypress/scripts/delete-reports.sh
This Pull request has e2e tests for validating error messages for mandatory fields on voyage report forms.
npm run cypress:test -- --spec cypress/integration/sGMR/voyage-report-form-validation.spec.js
\* Required
> COP-3232: Add tests for voyage report forms mandatory field validation

- src/components/People/FormPerson.jsx
Remove parentheses that were left after the error component refactoring (https://github.com/UKHomeOffice/sgmr-service/pull/162). 
\* Required
> Remove excessive parentheses from the voyage crew form

- src/components/PageContainer.jsx
- src/components/WelcomeBanner.jsx
- src/components/__tests__/WelcomeBanner.test.jsx
This branch adds a personalised welcome message to the home page of the service when the user has successfully logged in.
To test:
- run the app and API locally
- Sign in and on the home page (http://localhost:8080/reports) you should see a message "Welcome back, <user_name>" displayed at the top of the page.
\* Required
> COP-2144: User is given a welcome message on successful login

- cypress/integration/sGMR/account-deletion.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/support/commands.js
This PR has additional scenario for User account deletion functionality.
npm run cypress:test -- --spec cypress/integration/sGMR/account-deletion.spec.js
\* Required
> COP-3281: Add additional scenario for user account deletion functionality

- cypress/support/commands.js
This PR has Fix for the broken tests on master branch. Accidentally pushed an unwanted change in the previous PR which is causing failure on all the tests on master branch.
\* Required
> Remove reportPortal dependencies which are breaking tests on Master branch

- src/components/Banner.jsx
- src/components/LandingPage.jsx
- src/components/Main.jsx
- src/components/__tests__/Banner.test.jsx
- src/sass/main.scss
This branch adds the landing page for the service. It also updates the phase banner to beta.
- run locally and navigate to http://localhost:8080/
- Start page should now be displayed with link to Sign In page
\* Required
> COP-3351: Add landing page and update banner for Beta phase

- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
This PR has E2E test for adding report with more than one person on board. Test adds 3 people and select all of them to be included in the report.
npm run cypress:test -- --sepc cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
\* Required
> COP-3432: Add test for create report with more than one person on board

- cypress/integration/sGMR/sign-in.spec.js
- cypress/integration/sGMR/user-register.spec.js
This PR has e2e tests for user journey when user requests for new authentication code during Sign-in & Registration.
npm run cypress:test -- --spec cypress/integration/sGMR/sign-in.spec.js, cypress/integration/sGMR/user-register.spec.js
\* Required
> COP-2904: Add tests for User requesting new authentication code

- .babelrc
- package-lock.json
- package.json
- webpack.config.js
Enable async/await syntax.
Everything should work as before.
\* Required
> Enable async await

- src/components/Nav.jsx
Fix accessibility bug by enabling tab navigation for the sign out link.
Try accessing the `Signout` navigation item via tab key
\* Required
> COP-2957: Enable tabbing on the signout nav link

- src/components/Voyage/VoyageFormContainer.jsx
Fix accessibility bug by enabling tab navigation on the back link when saving voyage report.
When adding a new voyage report try to access the `< Back` link via tab key.
\* Required
> COP-2959: Enable tabbing on the back link when saving voyage

- src/components/User/UserInputCode.jsx
Update content for MFA SMS access code.
1. Provide sign-in details
2. Check if the content on the page used to enter the MFA code shows `6-digit` instead of `5-digit`
\* Required
> COP-3218: Update content for SMS access code

- src/components/Header.jsx
- src/components/Main.jsx
- src/components/People/CreateAPerson.jsx
- src/components/People/EditPerson.jsx
- src/components/User/DeleteAccount.jsx
- src/components/User/DeleteConfirmation.jsx
- src/components/User/EditAccount.jsx
- src/components/User/ForgottenPassword.jsx
- src/components/User/NewPassword.jsx
- src/components/User/UserRegister.jsx
- src/components/Vessel/EditVessel.jsx
- src/components/Voyage/VoyageFormContainer.jsx
Improve accessibility by adding an anchor to skip to the main content.
https://design-system.service.gov.uk/components/skip-link/
1. Open any page
2. Press "TAB" key
3. A yellow box should appear
4. Press "ENTER" key
5. The screen display now the main page content
\* Required
> COP-3217: Add a link used to skip to the page main content

- .babelrc
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/integration/sGMR/user-register.spec.js
- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- package-lock.json
- package.json
- src/components/Forms/validationRules.js
- src/components/Header.jsx
- src/components/Main.jsx
- src/components/Nav.jsx
- src/components/People/CreateAPerson.jsx
- src/components/People/EditPerson.jsx
- src/components/User/DeleteAccount.jsx
- src/components/User/DeleteConfirmation.jsx
- src/components/User/EditAccount.jsx
- src/components/User/ForgottenPassword.jsx
- src/components/User/NewPassword.jsx
- src/components/User/UserInputCode.jsx
- src/components/User/UserRegister.jsx
- src/components/Vessel/EditVessel.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
- webpack.config.js
Fix a bug preventing users from expanding the main navigation when browsing on mobile devices
1. Open the front page
2. Decrease the screen size to match a mobile device
3. Verify if the menu can be expanded
\* Required
> COP-2961: Fix expanding main nav on mobile devices

- .babelrc
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/integration/sGMR/user-register.spec.js
- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- package-lock.json
- package.json
- src/components/Forms/validationRules.js
- src/components/Header.jsx
- src/components/Main.jsx
- src/components/Nav.jsx
- src/components/People/CreateAPerson.jsx
- src/components/People/EditPerson.jsx
- src/components/User/DeleteAccount.jsx
- src/components/User/DeleteConfirmation.jsx
- src/components/User/EditAccount.jsx
- src/components/User/ForgottenPassword.jsx
- src/components/User/NewPassword.jsx
- src/components/User/UserInputCode.jsx
- src/components/User/UserRegister.jsx
- src/components/Vessel/EditVessel.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
- webpack.config.js
This reverts commit 91a4eb66fb108066329037f7cd7e2167a968f650.
Reverse https://github.com/UKHomeOffice/sgmr-service/pull/180 as the rebase "has gone wrong" and contained unwanted changes.
\* Required
> Revert "Fix expaning main nav on mobile devices"

- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- cypress/support/commands.js
- src/components/Dashboard.jsx
- src/components/Main.jsx
- src/components/ManageNotifications.jsx
- src/components/Nav.jsx
- src/components/PageContainer.jsx
- src/components/SectionTabs.jsx
- src/components/contentArray.js
- src/sass/main.scss
This branch updates the "homepage" of the service for the new designs. It changes the content/design and moves the notification overview tabs to a new page (called ManageNotifications). 
To test:
- Sign in and go to the home page (http://localhost:8080/reports) to see the new design. If you have any notifications already saved (draft / submutted etc) the numbers on the right should show this.
- Click on the Manage your notifications link under the numbers. This takes you to the new tabs page where you should see all existing notifications. 
- Make a new voyage or delete and existing one. When you navigate back to the homepage the numbers will have updated.
\* Required
> COP-3337: Put a new home page on dev

- src/components/Voyage/VoyageFormValidation.js
This branch updates the validation rules for creating a new person when submitting a voyage report. It makes it a requirement for the expiry date to be in the future and DOB in the past.
To test:
- Run the app locally, sign in and start a new voyage report. Navigate to the "People on board" page - http://localhost:8080/save-voyage/page-4 - and click link to add a new person. 
- Try to add a person with a DOB in the future or an expired document and you will see appropriate error messages. 
\* Required
> COP-2766 & 2764: New Person creation - fix validation for DOB and Travel doc expiry date

- src/components/Details.jsx
- src/components/User/PasswordField.jsx
- src/components/User/UserRegister.jsx
Add help text when choosing a password.
1. Go to the account registration form;
2. You should see an expandable help text under the password;
\* Required
> COP-3251: Add help text for choosing a valid password

- .drone-v1.yml
- .drone.yml
> COP2979-droneV1-fix

- cypress/integration/sGMR/edit-people.spec.js
This PR has tests for edit, save and not save existing people details.
npm run cypress:test cypress/integration/sGMR/edit-people.spec.js
\* Required
> COP-2900: Add tests for edit & save existing people details

- README.md
- cypress.env.json
- cypress.json
- cypress/config/dev.json
- cypress/config/local.json
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- cypress/plugins/index.js
- cypress/scripts/delete-reports.sh
- cypress/support/commands.js
- package-lock.json
- package.json
This Pull request has the setup to run e2e tests against different environments. For now, setup is done for local & dev environments.
npm run cypress:test:local
npm run cypress:test:dev
\* Required
> COP-3434: Setup Cypress tests to run against different environments

- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- cypress/support/commands.js
- index.html
- src/components/AccessibilityStatement.jsx
- src/components/Dashboard.jsx
- src/components/Forms/FormVoyageSubmitted.jsx
- src/components/LandingPage.jsx
- src/components/Main.jsx
- src/components/ManageReports.jsx
- src/components/Nav.jsx
- src/components/PrivacyCookiePolicy.jsx
- src/components/User/SignIn.jsx
- src/components/User/UserResendCode.jsx
- src/components/Vessel/CreateAVessel.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/FormSubmitted.jsx
- src/components/contentArray.js
This branch updates the service to ‘Submit a Pleasure Craft Report’. It also changes any reference to "Notifications" to "Reports" throughout the app and updates the tests for this change. 
To test:
- run the app locally. You will see the name of the service changed on Landing page, Nav bar, Dashboard, submission page, etc. See code for further details. 
- Run tests to check for these updates.
\* Required
> COP-3573: Rename the sGMR service

- cypress/integration/sGMR/user-register.spec.js
- src/components/Forms/__tests__/validationRules.test.js
- src/components/Forms/validationRules.js
- src/components/User/ForgottenPassword.jsx
- src/components/User/NewPassword.jsx
- src/components/User/UserRegisterValidation.jsx
- src/constants/ClientConstants.js
Make the password validation rules stricter.
1. Go to the registration form;
2. Try entering weak password to see if the validation is triggering errors;
\* Required
> COP-3244: Add stronger password validation

- cypress/integration/sGMR/user-register.spec.js
- cypress/support/commands.js
This PR has changes to start the E2E tests from the landing page. Executed all the tests on local & passed.
npm run cypress:test:local
\* Required
> COP-3504: Update E2E tests to start from the new Landing Page

- cypress/integration/sGMR/user-register.spec.js
This PR has tests to verify the new password validation rules and checks the correct error messages when password doesn't meet the criteria.
npm run cypress:test:local -- --spec cypress/integration/sGMR/user-register.spec.js
\* Required
> COP-3634 : Add E2E tests for Password validation rules

- cypress/integration/sGMR/user-register.spec.js
This PR has tests for validating mobile number on User registration Page. Tests would be added for the MFA resend authentication page once the validation added. 
npm run cypress:test:local -- --spec cypress/integration/sGMR/user-register.spec.js
\* Required
> COP-3764: Add test for mobile number validation on user registration page

- src/components/Voyage/PeopleSummary.jsx
Fix HTML markup to make the passenger details readable by screen readers.
\* Required
> COP-3219: Make passenger details accessible by screen readers

- src/components/People/FormPerson.jsx
- src/components/Voyage/PeopleSummary.jsx
This branch changes the roles for People from: 
Skipper, Paid Crew, Unpaid Crew >>> Skipper, Employed Crew, Unpaid Crew.
Note: this is only a change on the UI, the values being sent to the API are different because this is a CBP requirement (Skipper, Crew, Passenger).
To test: 
- Go to Add people page (http://localhost:8080/people/save-person?source=people) or add someone to a voyage and you'll see the new options. Also on the Check Voyage page. 
\* Required
> COP-3585: Update "Paid Crew" to "Employed Crew"

- cypress/integration/sGMR/add-people.spec.js
- src/components/Forms/validationRules.js
- src/components/People/CreateAPerson.jsx
- src/components/Voyage/VoyageFormValidation.js
- src/utils/date.js
This branch fixes the validation for date of birth and document expiry date when creating a new person. Previously, different error messages were showing when creating people on the Voyage Report or under the People section. These are now the same and the correct messages show depending on if you have entered no date or an invalid date. 
To test:
- Go to People page or create a Voyage Report, page-4 and create a new person. Try to submit with no DOB or doc expiry date and you will see error message 'You must enter a date of birth" or "You must enter an expiry date". Then try to enter a date that isn't valid for either field and you will get a different message saying to enter a valid DOB or doc expiry date.
\* Required
> COP-3268: Fix DOB and Document expiry date validation when creating new people

- cypress/integration/sGMR/add-voyage-report.spec.js
- src/components/Voyage/FormVoyagePeople.jsx
- src/components/Voyage/VoyageFormContainer.jsx
Show people on the manifest when selecting from saved people
1. Go to the voyage form
2. Add a new person to the manifest
3. For `Would you like to make further changes?` chose `Yes`
4. You should see text `People already added to the manifest:`
\* Required
> COP-3770: Show people on the manifest when selecting from saved people

- src/components/Main.jsx
- src/components/Vessel/EditVessel.jsx
- src/components/Vessel/FormVessel.jsx
- src/components/Vessel/VesselTable.jsx
Fixes a bug where input fields on the vessel edit page are not cleared.
1. Edit a vessel
2. Remove entire field value, e.g. vessel name
3. Check if the field is now empty, previously the original value reappeared
\* Required
> COP-3455: Fix text fields are not being cleared when editing vessel

- cypress/integration/sGMR/add-people.spec.js
- src/components/Forms/validationRules.js
- src/components/People/CreateAPerson.jsx
- src/components/People/FormPerson.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/VoyageFormValidation.js
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
- src/constants/ApiConstants.js
Validate ISO code of "Issuing state" when adding a new person.
Depends on a PR for sgmr-data-api.
1. Start `ref data` and `sgmr-data-api`
2. When adding a new person try filling a wrong ISO code, e.g. `LOL` and you should see and error
3. Filling a valid ISO code, e.g. `GBR` shouldn't raise an error
You should see details for the UK in the response
\* Required
> COP-2765: Validate ISO code when filling "Issuing state"

- cypress/integration/sGMR/edit-vessel.spec.js
This PR has tests for edit, save and exit without save an existing vessel. Tests are failing at the moment due to the issue, https://support.cop.homeoffice.gov.uk/browse/COP-3455. Once the issue fixed, these tests need to be re-run.
npm run cypress:test -- --spec cypress/integration/sGMR/edit-vessel.spec.js
\* Required
> COP-2895: Add tests for edit, save & exit without save existing vessel

- cypress/integration/sGMR/add-people.spec.js
- cypress/integration/sGMR/add-vessel.spec.js
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/edit-people.spec.js
- cypress/integration/sGMR/edit-vessel.spec.js
- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- cypress/support/commands.js
This PR has the E2E tests for editing details before submit the report. There is an outstanding issue (COP-3770) and this PR depends on the PR (https://github.com/UKHomeOffice/sgmr-service/pull/205).
npm run cypress:test:local -- --spec cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
\* Required
> COP-3490: Add E2E tests for edit details before submit the report

- .drone-v1.yml
- env.yaml
> COP-4123 Added mailslurp_api_key

- src/components/People/FormPerson.jsx
- src/components/Vessel/FormVessel.jsx
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/FormResponsiblePerson.jsx
Fixes the a11y accessibility issues to ensure all form inputs have a label.
\* Required
> COP-3801:Fix a11y issue of "Ensures every form element has a label"

- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormDeparture.jsx
Fix a11y issue of "Ensures every id attribute value used in ARIA and in labels is unique"
\* Required
> COP-3802: Fix a11y issues related to voyage form and IDs

- src/components/Voyage/FormCheck.jsx
> COP-3912: Update the titles on the voyage form check page to match those in the form

- src/components/Dashboard.jsx
- src/components/Help.jsx
> Fix bug on dashboard page

- src/components/AccessibilityStatement.jsx
Update contents of the accessibility statement.
\* Required
> COP-4056: Update a11y statement

- cypress/integration/sGMR/edit-people.spec.js
- src/components/Forms/validationRules.js
- src/components/People/CreateAPerson.jsx
- src/components/People/EditPerson.jsx
- src/components/People/FormPerson.jsx
Add missing validation when editing an existing person.
\* Required
> Fix missing validation when editing a person

- .drone-v1.yml
- cron-Dockerfile
- cypress/fixtures/user-registration.json
- cypress/fixtures/users.json
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/password-reset.spec.js
- cypress/integration/sGMR/report-form-validation.spec.js
- cypress/support/commands.js
- env.yaml
- kube/job.yml
- kube/secret.yml
- scripts/run-test.sh
This PR has changes to setup a CRON job on Kubernetes cluster to run e2e tests against Dev env on periodically.
Also Updated the assertion to check number of reports added. MailSlurp Email address updated.
kubectl --context=acp-notprod_COP --namespace=cop-sgmr-dev get cronjobs
There should be a job created with name "sgmr-e2e-tests-cron" and it would schedule a pod every one hour  between 8am to 6pm to run e2e tests.
kubectl --context=acp-notprod_COP --namespace=cop-sgmr-dev logs pod/nameofthepod
\* Required
> COP-4558: Create CRON job to run e2e tests periodically against DEV env

- package-lock.json
- package.json
- src/components/500.jsx
- src/components/Main.jsx
Creation of a 500 page. Resubmitted as previous branch had some unsigned changes
\* Required
> 500 service unavailable

- .drone.yml
This PR has the fix for cronjob failure of sGMR e2e tests.
\* Required
> Fix sGMR e2e tests cronjob failure

- .drone.yml
- env.yaml
> COP-5504 drone pipeline update

- env.yaml
> COP5560-Adding maintenance variable

- Dockerfile
- nginx/run.sh
- src/components/Help.jsx
- src/components/Main.jsx
- src/config.js
- src/constants/ApiConstants.js
- webpack.config.js
1. Build the docker image 
```
docker build -t sgmr-service .
```
2. Start the container 
```
docker run --rm -it -p 8080:8080 --env SGMR_MAINTENANCE=true --env SGMR_DATA_API_BASE_URL=http://localhost:5000/v1 sgmr-service
```
3. You should see a maintenance page at http://localhost:8080/
4. Running the container with maintenance mode off should display app's normal functionality
```
docker run --rm -it -p 8080:8080 --env SGMR_MAINTENANCE=false --env SGMR_DATA_API_BASE_URL=http://localhost:5000/v1 sgmr-service
```
\* Required
> Fix the maintenance mode

- src/config.js
> COP-6795 Api url short term fix

- src/components/Forms/validationRules.js
- src/components/Voyage/VoyageFormValidation.js
Skipper's phone number needs validation so that no letters could be included. It also needs to allow for international numbers, so any number of integers and +, ' ', () are accepted.
\* Required
- [x ] Pull request URL linked to JIRA ticket? \*
> Add validation to skipper phone number

- src/components/WelcomeBanner.jsx
- src/components/__tests__/WelcomeBanner.test.jsx
Change heading on the main reports page from a h3 header to a paragraph
* Go to the main reports page
* You should see the text which welcomes the user back as a paragraph (was previously a header)
\* Required
> SPCR-105: Change heading on the main Reports page to a paragraph

- src/components/Voyage/FormCheck.jsx
Make section titles into h2 tags instead of dt tags.
Make 'change' text links into 'change + [section title]' 
Review the position of the 'change' links being moved under each of the sections.
\* Required
- [ x] Pull request URL linked to JIRA ticket? \*
> SPCR-99 Make section titles <h2> and change link text & position

- src/components/User/UserRegister.jsx
Change Declaration heading on the UserRegister (Create an Account) page to h2 from h3
\* Required
- [ x] Pull request URL linked to JIRA ticket? \*
> SPCR-106 Change Declaration heading hierarchy

- src/components/Voyage/PeopleTable.jsx
Given that we don’t see our users needing to select large lists of people they are sailing with, we want to remove this functionality for “select all” for now, leaving the user with the ability to select multiple single people.
\* Required
- [x ] Pull request URL linked to JIRA ticket? \*
> SPCR-101 Remove select all tickbox on list of people

- src/components/People/FormPerson.jsx
Remove the aria-describedby gender-hint on 'Add details of a new person' page
\* Required
- [x ] Up-to-date with master branch? \*
- [ x] Pull request URL linked to JIRA ticket? \*
> SPCR-103 Remove gender hint

- src/components/PageAccount.jsx
- src/components/User/EditAccount.jsx
- src/components/User/UserRegister.jsx
Service now asks the user for a telephone number instead of a mobile number as this is more in line with current GDS guidelines.
* Go to Create an Accounts page
* You should see a telephone number label
Or
* Go to Account page
* You should see a telephone number label
\* Required
> SPCR-118 Replace all instances of 'mobile number' with 'telephone number'

- package-lock.json
- package.json
Remove Winston package as not used in this project
\* Required
> SPC-89 [2] Remove Winston

- package-lock.json
- package.json
- webpack.config.js
Update to webpack 5
also requires update for wepack-cli
and removing node-sass to be replaced with sass
\* Required
> SPC-89 [9] Update webpack, webpack-cli, sass (remove node-sass)

- package-lock.json
- package.json
- src/lib/polyfills.js
Remove remaining unused packages
\* Required
> SPC-89 [3] Remove unused packages

- src/components/User/__tests__/EditAccount.test.jsx
- src/components/Voyage/FormResponsiblePerson.jsx
- src/components/Voyage/__tests__/FormResponsiblePerson.test.jsx
- src/components/Voyage/__tests__/VoyageFormDataFormatting.test.js
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
- src/components/__tests__/Banner.test.jsx
- src/components/__tests__/ErrorSummary.test.jsx
- src/components/__tests__/PageAccount.test.jsx
- src/components/__tests__/WelcomeBanner.test.jsx
Updating tests to the preferred describe/it syntax in preparation for updating React Testing Library and Jest
\* Required
> SPC-89 [5] Update tests to use describe/it syntax

- src/components/User/EditAccount.jsx
Service now validates telephone number inputs when it is entered on the Edit Account page
\* Required
> SPCR-122 Add phone validation to EditAccount.jsx

- src/components/User/EditAccount.jsx
Validation/error handling for the first and last name inputs does not visualise the errors on the front end and the error summary is not functioning anymore on the edit account page. Add error classes to first and last name inputs and show error summary above the inputs.
- Sign in and click on the edit account page.
- Remove all text inputs
- Save changes
- There should be an error summary and errors on the inputs
- Type letters into the phone number input
- There should be a valid number error
- Return original text inputs
- Save changes
- This should submit
\* Required
> SPCR-127 Edit validation/error handling for EditAccount page

- src/components/Forms/validationRules.js
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
Change wording of error messages as they were inconsistent - **a** to **your**
E.g. You must enter **a** first name & You must enter the first name of **your** address 
* Create a new PCR
* Go to Add Skipper details page
* Leave address lines blank and click save and continue
* You should see an error - “You must enter a first address line"
\* Required
> SPCR-135 Change error labels on skipper details

- src/components/contentArray.js
Change 'surname' and 'given name' to 'last name' and 'first name' respectively, as first/last name is used throughout the rest of the application.
* Go to People tab
* You should see First Name and Last Name as headings on the People table
\* Required
> SPCR-138 Change wording of people table on 'People' tab

- src/utils/date.js
- src/utils/time.js
Discovered missed removing the ' from the regex
\* Required
> Fix RegEx formatting

- package-lock.json
- package.json
Remove enzyme as it is not used (we use Jest/React Testing Library)
- remove package-lock and node-modules
- `npm i`
- `npm start`
- > app should compile
- `npm run lint -- .` (for all files)
- > there should be no lint errors
- `npm test`
- > tests should run without error
\* Required
> SPCR-161 Remove enzyme as package not used

- package-lock.json
- package.json
an outdated version of browserslist was in our dependency
We do not need it there, it's included in babel where it is used, and babel installs the version it needs
- remove package-lock and node-modules
- `npm i`
- `npm start`
- > app should compile
- `npm run lint -- .` (for all files)
- > there should be no lint errors
- `npm test`
- > tests should run without error
\* Required
> SPCR-162 Remove browserslist as a dependency

- src/components/User/EditAccount.jsx
- src/components/User/__tests__/EditAccount.test.jsx
We are aiming for 90% test coverage. Tests need to be added to increase this coverage by testing the error functionality
- Run `npm test`
Check tests are testing correctly
\* Required
> SPCR-153 Increase unit test coverage for EditAccount.jsx

- package-lock.json
- package.json
Update webpack-dev-server & webpack-cli to address glob-parent vulnerability
- remove package-lock and node-modules
- `npm i`
- `npm start`
- > app should compile
- `npm run lint -- .` (for all files)
- > there should be no lint errors
- `npm test`
- > tests should run without error
\* Required
> SPCR-88 Update webpack-dev-server and webpack-cli

- src/components/Forms/__tests__/validationRules.test.js
- src/components/Forms/validationRules.js
Review what is currently covered by unit tests and add more as required
Add tests for the validate function
Remove dateValidation as this is not used in the application
- Run `npm test`
Check tests are testing correctly
\* Required
> SPCR-151 Increase unit test coverage for validationRules.js

- src/utils/__tests__/date.test.js
We are aiming for 90% coverage, and need to review what is currently covered by unit tests and add more as required. Add tests to test the date formatting and validation.
- Run `npm test`
Check that tests are testing correctly 
\* Required
> SPCR-165 Increase unit test coverage for Date.js

- src/components/__tests__/PortField.test.jsx
This PR adds more tests to increase the coverage for the `PortField` component. It does not introduce any new functionality
\* Required
> SPCR-190 Increase test coverage for PortField component

- src/components/User/UserRegisterConfirmation.jsx
Add ability for a user to request another verification email from this page if they did not receive the first email
- Complete the registration form and go to the confirmation screen
- There should be a link to resend email verification
- Click on the resend email verification link
- A new email verification should be sent and a new confirmation message should appear on screen
\* Required
> SPCR-141 Add resend email link to userRegistrationConfirmation

- src/components/DeleteEntity.jsx
- src/components/Main.jsx
- src/components/People/EditPerson.jsx
- src/components/People/FormPerson.jsx
Add ability to be able to remove/delete people that have been saved previously to keep an up to date list of saved people.
When clicking on a person to edit it, there should be a button to delete the person. When this is clicked a page should appear asking if you are sure. When yes is clicked, the person is deleted and the people page will have a notification banner at the top with a success message.
- Go to the people page
- Click on a saved person and scroll to the bottom
- Click the delete button
- This should take you to a page asking if you are sure.
- Click yes and then continue
- You should be redirected to the people page with a success banner at the top
- Click another tab, and back to saved people
- This banner should no longer be visible
\* Required
Ensure you delete the branch …
> SPCR-65 Add functionality to delete a person

- cypress/fixtures/user-registration.json
- cypress/fixtures/users.json
- cypress/integration/sGMR/add-people.spec.js
- cypress/integration/sGMR/edit-people.spec.js
- cypress/integration/sGMR/password-reset.spec.js
- cypress/support/commands.js
- cypress/support/index.js
- cypress/support/utils.js
- package-lock.json
- package.json
- update mailslurp details
- update syntax changed with upgrade to Cypress v9
- update add people tests as some terminology has changed
- run `npm ci` (new package for Cypress tables added)
- add apiKey
- run `npm run cypress:runner -- --env configFile=dev`
- run tests for **add people**
- > tests should pass
Note cypress-get-tables has some vulnerabilities, added to ticket to investigate these
\* Required
> SPCR-291 Update Cypress & fix add people tests

- src/constants/ApiConstants.js
Currently we receive 10 reports per user. This is fine for production & we are working on a paginated solution to enable us to return more than 10 consistently.
However any user testing in staging needs to be able to handle more than 10 reports to be able to complete all their scenarios.
So updating config for this version to go to staging and we can revert it before going to production
https://viabledata.atlassian.net/browse/SPCR-225
\* Required
> Increase number of reports returned from API for testing purposes

- src/components/WelcomeBanner.jsx
- src/components/__tests__/WelcomeBanner.test.jsx
Welcome banner has incorrect styling
- update welcome banner to be `h3` with `govuk-heading-m` class
- update unit test to test for the required style
\* Required
> SPCR-207 Make welcome message a h3 medium title

- src/components/Forms/__tests__/validationRules.test.js
- src/components/User/__tests__/UserRegister.test.jsx
- src/components/User/__tests__/UserRegisterValidation.test.jsx
Review tests and ensure that all input scenarios for password validation are covered. New tests for UserRegister.jsx and UserRegisterValidation.jsx have also been created.
- Run `npm test`
\* Required
> SPCR-189 Update tests for account creation page

- index.html
- package-lock.json
- package.json
- src/components/Main.jsx
- src/index.jsx
- remove matomo tags
- add GA tags
- add React GA package to enable pageviews being passed to GA
\* Required
> SPCR-181 Replace Matomo with GA

- cypress/integration/sGMR/add-people.spec.js
- cypress/integration/sGMR/add-vessel.spec.js
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/edit-people.spec.js
- cypress/integration/sGMR/edit-vessel.spec.js
- cypress/integration/sGMR/my-account.spec.js
- cypress/integration/sGMR/password-reset.spec.js
- cypress/integration/sGMR/report-form-validation.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/integration/sGMR/voyage-account-deletion.spec.js
- cypress/support/commands.js
- swapped localStorage to sessionStorage as that's what we use now
- updated tables to include titles in the expect as they exist in the text but are hidden on desktop (shown on mobile)
- pull down
- update `mailSlurpApiKey`
- run `npm run cypress:runner -- --env configFile=dev`
- run `add-people-spec` test
- > this test should pass
\* Required
> SPCR-219 Update to make add-people Cypress tests work

- cypress/integration/sGMR/add-people.spec.js
- cypress/integration/sGMR/add-vessel.spec.js
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/support/commands.js
- swapped localStorage to sessionStorage as that's what we use now
- updated tables to include titles in the expect as they exist in the text but are hidden on desktop (shown on mobile)
- update error class name
- add remove test data function
- pull down
- update `mailSlurpApiKey`
- run `npm run cypress:runner -- --env configFile=dev`
- run `add-people.spec` test
- run `add-vessel.spec` test
- run `add-voyage-report-with-saved-data.spec` test
- run `add-voyage-report.spec` test
- run `edit-existing-details-report-before-submit.spec` test
- run `voyage-account-deletion.spec` test
- > these tests should pass
\* Required
> SPCR-219 Update Cypress tests for voyages

- kube/cert.yml
> cop-10098 Update for cert-manager upgrade

- src/components/ManageReports.jsx
- src/components/__tests__/ManageReports.test.jsx
SPCR-298 needed to be redone, with the statuses not being added as new tabs but incorporated into the existing ones.
- Go to the view existing voyage plans page
- You should see 3 tabs again
- Failed reports should appear under the submitted tab
\* Required
> SPCR-309 Fix voyage plan tabs

- .drone.yml
- package.json
- sonar-project.properties
updated config to integrated with sonarqube
sonar dashboard
https://sonarqube.digital.homeoffice.gov.uk/dashboard?id=cop-sgmr-service
drone build
https://drone-gh.acp.homeoffice.gov.uk/UKHomeOffice/sgmr-service/2605
> Cop 9560 sonarqube fix

- kube/deployment.yml
> increased cpu and memory resources

- src/components/Voyage/VoyageFormContainer.jsx
The validation code that we originally needed for managing port names is no longer needed with the new port fields. It's now causing errors on other pages so this PR removes it
- create a new voyage report
- fill in all the pages
- submit the report
- > you should be able to submit 
\* Required
> Remove unneeded validator as it's causing errors

- src/components/LandingPage.jsx
Implemented changes to landing page based on design below
- Go to landing page
- It should match above design
- Check that links work appropriately
\* Required
> SPCR-344 Add links to relevant advice pages

- cypress/config/dev.json
- cypress/fixtures/user-registration.json
- cypress/fixtures/users.json
- cypress/integration/sGMR/add-people.spec.js
- cypress/integration/sGMR/add-vessel.spec.js
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/edit-people.spec.js
- cypress/integration/sGMR/edit-vessel.spec.js
- cypress/integration/sGMR/my-account.spec.js
- cypress/integration/sGMR/password-reset.spec.js
- cypress/integration/sGMR/report-form-validation.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/integration/sGMR/voyage-account-deletion.spec.js
- cypress/support/commands.js
> Dev environment updated tests

- src/components/SectionTablePeople.jsx
- src/components/Voyage/FormVoyagePeople.jsx
- src/components/Voyage/__tests__/FormVoyagePeople.test.jsx
- src/pages/people/PersonForm.jsx
- src/pages/people/__tests__/PersonForm.test.jsx
- src/utils/v2ApiHooks.js
- start a voyage
- enter departure, arrival, and pleasure craft
- click `add new person`
- > you should be taken to the people form
- > there should be NO delete button on the form
- click `exit without saving`
- > you should be taken back to the voyage form with no new people
- enter a persons details
- click continue
- click submit
- > you should be taken back to the voyage form
- > you should see your new person in the list and be able to tick to add them to the voyage
\* Required
> SPCR-314 Use new people form to add a person during voyage

- .drone.yml
- env.yaml
Update environment variables, secrets, and branch trigger (i.e. from "spcr" to "master").
N/A
N/A
---
> Rename from sGMR to sPCR

- webpack.config.js
Add var to webpack so it builds and can be replaced with value from secrets
---
> Add missing var

- README.md
- cypress/config/dev.json
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/edit-people.spec.js
- cypress/integration/sGMR/edit-vessel.spec.js
- cypress/integration/sGMR/report-form-validation.spec.js
- cypress/integration/sGMR/user-register.spec.js
- cypress/scripts/delete-reports.sh
- scripts/env-setup.sh
> Tests to delete the saved pleasure craft and people

- cypress/config/dev.json
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/user-register.spec.js
> TestsAdded -To submit voyage report from saved draft

- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/edit-people.spec.js
- cypress/integration/sGMR/edit-vessel.spec.js
- cypress/support/commands.js
> Submit the cancelled voyage plan

- env.yaml
Added the secret to the env file so that it can be pulled in from secrets manager from drone.yaml.
Run Deployment for sgmr-service.
Part of sgmr to spcr rename.
---
> SPCR-8075: Add gov_notify_support_email secret

- env.yaml
> Release version 1.2.1

- env.yaml
Update env.yaml to name the secret correctly
Run Deployment.
---
> Update secret var to be named correctly

- env.yaml
> Release version 1.2.2

- .drone.yml
- env.yaml
> Version 1.2.3
