UKHomeOffice/sgmr-service

- kube/deployment.yml
Removes the quotes from the port line, making it an integer as expected
> Remove quotes from the port setting

- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/VoyageFormContainer.jsx
TO TEST
- Go to /reports
- Go to start now
- Fill in at least the date on the departure page
- Click save and continue
> you should see page 2 - arrival
- Enter valid data in some or all the fields
- Click save and continue
> you will be taken to a blank page 3
> you should be able to see in network tab that the voyage data was updated
**I can edit my arrival details**
- click on a voyage
> you should be taken to the check details page
- click change next to arrival details
> you should be taken to the arrival page with your saved details populated
- edit/add/delete something
- click save and continue
> you should be taken to page 3 (blank)
- click on your voyage
> you should be taken to the check details page with your changes saved
NOTE: Full validation …
> Add arrival page

- src/components/SectionTabs.jsx
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/VoyageFormContainer.jsx
**EXIT WITHOUT SAVING**
- Exit without saving option on all form voyage page
TEST
- On click returns you to /reports without changes being saved
- NOTE: manifest will already be saved
——
**CANCEL DRAFT VOYAGE**
- Cancel button on check page
TEST
- On click returns you to /reports
- Your voyage should be listed under the cancelled tab
----
**HIDE INVALID REPORTS**
- if report has an invalid departureDate (aka user clicked 'save voyage' button but did not progress past page 1 save and continue, hide those from the report page
TEST
- click on save voyage
- click on /reports
> You should not see any Invalid Date reports
NOTE: This PR does not send any status update or delete request to the API to remove these
> Cg 121 exit cancel

- src/components/Footer.jsx
- src/components/Main.jsx
- src/components/PrivacyCookiePolicy.jsx
This branch adds the Privacy and Cookie policy page to the service and updates the footer to include a link to this, and placeholder links fo the Accessibility statement / Help pages (these are to follow). 
- clone and run the app. 
- navigate to the footer and click the Privacy and Cookie Policy link. 
- Content should display as defined by business (see ticket: https://support.cop.homeoffice.gov.uk/browse/COP-2510)
\* Required
> COP-2510: Add Privacy and Cookie Policy page

- src/components/AccessibilityStatement.jsx
- src/components/Main.jsx
This branch adds a page for the service's Accessibility statement and a link within the footer. The content is defined here: https://support.cop.homeoffice.gov.uk/browse/COP-2513
To test:
- run the service locally and navigate to: http://localhost:8080/accessibility-statement or click the link in the footer.
- content should be displayed as defined in the word document in the ticket above.
\* Required
> COP-2513: Add Accessibility Statement page to the service

- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- src/components/Forms/validationRules.js
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
This branch updates the last page of the voyage report form ("Check fields" page) so that a user cannot submit a voyage with no responsible person on board by making this field mandatory. Before this change, a user could save an incomplete voyage with no responsible person as a Draft, access it from the Drafts tab on dashboard page and submit it. This branch also updates the naming conventions from Given name to first name, surname to last name and fixed the tests. 
- run project locally. Sign in and navigate to home page. 
- Start a new voyage report: fill in the details for pages 1-4 but do NOT save any Skipper details on http://localhost:8080/save-voyage/page-5. Click Exit without saving at the bottom. 
- This will take you back to the home page. You should see your incomplete voyage …
> COP-3189: Update Voyage Check page

- src/components/Forms/validationRules.js
- src/components/User/UserRegister.jsx
- src/components/User/UserRegisterValidation.jsx
- src/components/Vessel/FormVessel.jsx
This branch marks the fields on the create a vessel page as optional and adds validation to the mobile number when a user registers (allows numbers and whitespaces only).
To test:
When signed out, attempt to register a user with a phone number that contains anything other than a digit or whitespace. Submit and you will see an error message.
Navigate to the create a vessel page (http://localhost:8080/vessels/save-vessel?source=vessels) - you will see optional on the relevant field labels.
\* Required
> COP-3190 & COP-2758: Add mobile number validation and mark vessel fields as optional

- src/components/ManageReports.jsx
Fixes an issue when user is unable to tab between draft, submitted and cancelled tabs (keyboard only navigation).
1. Go to the homepage
2. Click View existing reports
3. Try switching between tabs using only keyboard
\* Required
> COP-2958: Fix a11y issue of report tabs not accessible by keyboard

- .eslintrc.js
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/voyage-report-form-validation.spec.js
- cypress/scripts/delete-reports.sh
- cypress/support/commands.js
- cypress/support/index.js
- package-lock.json
- package.json
- src/components/PortField.jsx
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/constants/ApiConstants.js
- src/sass/main.scss
Replace a simple input field for arrival/departure port with an autocomplete widget.
Depends on https://github.com/UKHomeOffice/ref-data-api/pull/179
1. Make sure the backend PR is merged (GitLab)
2. Start creating voyage 
3. On the arrival and departure form steps you should see an autocomplete widget for port entry
\* Required
> COP-2488: Replace the departure/arrival port input with autocomplete

- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- index.html
- src/components/ManageReports.jsx
This branch updates the Manage Reports page to be suitable for mobile devices. Beforehand the table would overflow for smaller screen sizes - confirmed with Christina that the Departure Time and Submission reference do not need to be displayed in the overview table so removed these. Also update the Matomo code to the prod url. 
To test:
- visit http://localhost:8080/manage-reports and inspect at different screen sizes. 
\* Required
> COP-2962/COP-4076: Update Manage Reports page to be mobile responsive and update Matomo code

- src/components/People/FormPerson.jsx
- src/components/Voyage/VoyageFormDataFormatting.js
This branch addresses the bugs flagged in:
- COP-4355 : the Port of Registry on the Vessel page was not being fed through in the data package when a voyage is submitted
- COP-4356 :  the "Other" option under Travel Document details on the Add a  Person page was not clickable
To test: 
- Submit a voyage selecting the "Other" option for Travel document when adding a new person, and fill in the Port of Registry on the Vessel page. These will now be correctly populated on the check page and submitted correctly.
\* Required
> COP-4355/6: Fix bugs on Vessel and People page

- cypress/integration/sGMR/add-people.spec.js
- cypress/support/index.js
This PR has Fix for the Screenshots attachment for the failed tests.
npm run cypress:test:report -- -e local  -m <MailSlurp_API_Key>
After the test execution, navigate to folder mochawesome-report and open mochawesome.html to see the reports.
\* Required
> Attach Screenshots for the failed tests in the Mochawesome report

- src/components/Forms/FormVoyageSubmitted.jsx
- src/components/User/EditAccount.jsx
- src/components/__tests__/PageAccount.test.jsx
Fix incorrectly coded labels so that they can be read by a screen reader
* Go to Edit Account page
* Enable a screen reader
* Click on an empty text field
* You should be able to hear the label being read out by the screen reader
\* Required
> SPCR-104: Fix text input labelling on Edit Account page

- src/components/People/FormPerson.jsx
Only display the text input for capturing “other” details if the “Other” radio control option has been selected.
Remove the “If “Other”” part of the label.
This change should effect both page 4b in the form and save a new person on people tab.
-Go to page 4 on form (People on your voyage) and click on add a new person OR click on the people link and 'Save a person'
-Scroll to document type and click 'other'
-An input text field should appear
-This field should disappear if another document type is clicked
\* Required
- [x ] Pull request URL linked to JIRA ticket? \*
> SPCR-102 Add conditional text input to Other radio input

- src/components/Forms/validationRules.js
- src/components/Voyage/FormResponsiblePerson.jsx
- src/components/Voyage/__tests__/FormResponsiblePerson.test.jsx
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
Make the second line of the address optional and add a label informing users it is optional.
Warning: This has the potential to break after refactoring error handling as there is a chance backend validation isn't being reached currently. 
Go to the Add Skipper's address page (6 of 7)
Scroll to Address
The second input field should have an optional label
Leave this input empty
Submit the form
No error should occur for this input
The form should also submit when this input has text
\* Required
> SPCR-100 Update address pattern, make second line optional

- src/components/LandingPage.jsx
When the user is signed in and clicks on the GOV logo it takes them to the landing page; after clicking start now, they are taken back to the sign in page. If the user is already signed in this button should take them back to the dashboard and only if they are not signed in should it direct them to the sign in page.
- When signed out, click the GOV logo
- Then click the 'Start now' button
- This should redirect to the sign in page (/sign-in)
- Enter sign in details
- Click the logo again
- Then click start now
- This should now redirect to the dashboard (/reports)
\* Required
> SPCR-123 Edit routing for landing page

- src/components/People/FormPerson.jsx
- src/components/Voyage/FormVoyagePeople.jsx
- src/components/Voyage/FormVoyagePeopleManifest.jsx
We have new user flows being tested with users. In the meantime, we should take the content on the prototype and update the existing pages on the service to match.
All user-visible mentions of "manifest" have been replaced by “voyage plan”.
- Go to any page which would have previously contained "manifest"
- Ctrl + F in your browser and type "manifest"
- You should get no results
- Ctrl + F in your browser and type “voyage plan”
- You should get at least one result
\* Required
> SPCR-145 Rename 'manifest' to 'voyage plan'

- package-lock.json
- package.json
- webpack.config.js
Update copy-webpack-plugin
The latest version: 10.x requires webpack 5 which we cannot update to yet (docker image is on 4)
However we only need to go to version 6 to address glob-parent vulnerability
- remove package-lock and node-modules
- `npm i`
- `npm start`
- > app should compile
- `npm run lint -- .` (for all files)
- > there should be no lint errors
- `npm test`
- > tests should run without error
\* Required
> SPCR-88 Update copy-webpack-plugin to version 6

- cypress/integration/sGMR/add-vessel.spec.js
- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/edit-vessel.spec.js
- cypress/integration/sGMR/report-form-validation.spec.js
- cypress/support/commands.js
Certain words and phrases within the service have been refactored. This should also be done to the Cypress tests, otherwise they will throw an error.
All UI instances of ‘vessel’ have been replaced with ‘pleasure craft’ within the Cypress tests.
\* Required
> SPCR-202 Rename 'vessel' to 'pleasure craft' (Cypress)

- cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/report-form-validation.spec.js
- cypress/integration/sGMR/sign-in.spec.js
- cypress/support/commands.js
Certain words and phrases within the service have been refactored. This should also be done to the Cypress tests, otherwise they will throw an error.
All UI instances of ‘report’ have been replaced with ‘voyage plan’ within the Cypress tests.
\* Required
> SPCR-202 Rename 'report' to 'voyage plan' (Cypress)

- cypress/integration/sGMR/add-voyage-report.spec.js
- cypress/integration/sGMR/edit-existing-details-report-before-submit.spec.js
- cypress/integration/sGMR/report-form-validation.spec.js
Certain words and phrases within the service have been refactored. This should also be done to the Cypress tests, otherwise they will throw an error.
All UI instances of ‘manifest’ have been replaced with ‘voyage plan’ within the Cypress tests.
\* Required
> SPCR-202 Rename 'manifest' to 'voyage plan' (Cypress)

- src/components/Voyage/VoyageFormValidation.js
- src/utils/__tests__/time.test.js
- src/utils/time.js
When a user types in the current date with a time in the past on a departure or arrival form, the error message previously popped up next to the date input as opposed to the time input where it should be, as the date is valid but the time is not. This PR fixes this issue.
- Go to Voyage Plans Dashboard
- Start a new report
- Enter a date and time in the past
- Click Save and continue
- You should get an error on the date input
- Change the date to the current date while keeping the time before the current time
- Click Save and continue
- You should get an error on the time input
- Change the time to one in the future
- Click Save and continue
- You should not get errors on the date or time inputs
\* Required
> SPCR-199 Fix error placement on departure and arrival forms

- src/assets/main.scss
- src/components/Voyage/PeopleTable.jsx
The positioning of the check box in mobile view when viewing the responsive tables should be fixed as it was placed in an odd position.
- Go through the voyage form
- Go to the people on board page
- Add a new person on board
- Switch to a mobile view
- The table should look like the screenshot below 
\* Required
> SPCR-248 Fix checkbox layout in responsive tables

- src/components/Dashboard.jsx
- src/components/Main.jsx
- src/components/Nav.jsx
- src/pages/help/Help.jsx
- src/pages/help/__tests__/Help.test.jsx
- add help page
- use help page as first page in voyage journey
- hide continue/cancel buttons if viewing help page from anywhere other than voyage start
- log in
- start a voyage
- > first page should be new help page
- click cancel
- > you should be returned to the dashboard
- start another voyage
- click continue
- > departure details page should load
- complete this page and continue
- return to dashboard
- view voyage plans
- > the plan you just started should be visible in the draft list
\* Required
-  [x] Does it have tests?
> SPCR-10 Add help/voyage start page

- package-lock.json
- package.json
- src/assets/main.scss
- src/components/Dashboard.jsx
- src/components/ManageReports.jsx
- src/components/Pagination.jsx
- src/components/__tests__/Pagination.test.jsx
- src/constants/ApiConstants.js
- src/lib/config.js
- src/utils/usePagination.js
Pagination is needed on the manage voyage plans plan for when the number of voyage plans is greater than 10 (sum of drafts, cancelled and submitted). If there are already 10 voyage plans, when a user creates another, it does not appear in the UI. Pagination is needed to view all voyage plans associated with a users account.
This is a version of pagination that works without the need for the backend changes. This version will paginate all voyage plans regardless of status (even those with a 'failed' status, which will not appear in the UI). When the backend work is completed, this version of pagination will be updated to paginate according to the statuses of the voyage plans, rather than paginate them simultaneously. 
- From the dashboard, click on 'View existing voyage plans' 
**(If you …
> SPIKE-Pagination: Implement a version of pagination (without BE changes)

- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/__tests__/FormCheck.test.jsx
Currently if a voyage is of the state cancelled or precancelled, when a user views this voyage, the ‘check’ page has the option to submit, cancel and exit without saving. If a voyage is cancelled, these CTAs should not be visible. 
- Click on 'View existing voyage plans'
- Go to the cancelled tab
- (If there are no cancelled reports, make a report and cancel it)
- Click on a cancelled report
- Scroll to the bottom
- There should be no submit, cancel or exit without saving visible
- Drafts and Submitted reports should still have these CTAs (for now at least)
\* Required
> SPCR-243 Remove actions that allow user to cancel a cancelled voyage

- src/components/Dashboard.jsx
- src/components/__tests__/Dashboard.test.jsx
Currently, when a voyage plan is submitted but receives the status of `failed`, this voyage is not shown in the UI. The user should not know that the submission has failed, therefore we need the `submitted` counter to increase after a submitting a voyage plan, even if it has the status of failed. 
\* Required
> SPCR-291 Increase the count of 'Submitted' reports in failure scenario

- src/assets/LoadingSpinner.scss
- src/assets/main.scss
- src/components/LoadingSpinner.jsx
- src/components/ManageReports.jsx
- src/components/__tests__/LoadingSpinner.test.jsx
- src/components/__tests__/ManageReports.test.jsx
Currently, the application does not have a loading spinner, so when the user has low connectivity, there is no indication that something is loading in the background. A loading spinner should be added where there is asynchronous code to let the user know they have to wait while something is loading, rather than some content being blank during this time.
- Go to the manage reports page
- Inspect the page and then click on the network tab
- Click on the dropdown that says 'not throttling' and select 'slow 3G'
- Click on 'next' on the pagination
- An animated loading spinner should appear
- It should disappear when the voyage plans have loaded
\* Required
> SPCR-302 Add a loading spinner component

- src/components/PortField.jsx
We were previously making GET calls on render
We want to only make a call once at least 3 letter are typed
- Go to an autocomplete field (departure/arrival port form)
- Type one letter
- No suggestions or get calls are made
- Type two letters
- No suggestions or get calls are made
- Type three letters
- Get calls are made and suggestions are made if available
\* Required
> SPCR-328 GET port list only after 3 characters typed for autosuggest field

- src/assets/main.scss
- src/components/ManageReports.jsx
- src/components/PortField.jsx
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormCheck.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/VoyageFormContainer.jsx
- src/components/Voyage/__tests__/FormArrival.test.jsx
- src/components/Voyage/__tests__/FormDeparture.test.jsx
- src/utils/formatPortData.js
- Branches from https://github.com/UKHomeOffice/sgmr-service/pull/399 as extends on that functionality
- extending test coverage in SPCR-304
This PR
- extends on the autocomplete functionality to
- - throw error when user changing fields from valid value to null value
- - clear select list from view when selection made
- adds the port name to display along with unlocode in departure and arrival port
- - inputs
- - check answers page
- - manage reports page
- you need SPCR-304 and run `npm ci` to ensure autocomplete package is available
- create a new voyage
- enter a port in the autocomplete field
- select a port from the list
- go to next page
- go back
- > port should show name and unlocode (if selected port has a code) or name (if selected port has no code)
- delete the port
- try to …
> 1.1.0 SPCR-288 Show port names as well as unlocodes

- src/components/PortField.jsx
**This ticket also solves SPCR-321, as they both require the same solution**
> While a user is creating a new voyage, the screen reader reads the arrival point field as a combo box and to change the selection the user should use the arrow keys. However, using the arrow keys does not select an arrival point, the user has to begin to type in an arrival point and select the point from the dropdown list.
> 
> The user is able to use the arrow keys to navigate through the dropdown list but must begin typing an arrival point first for this to happen. Therefore the visually impaired user may become confused as to how to select an arrival point.
This ticket solves the above issue by changing the aria label to instruct the user that they must type in order for port selections to appear.
- Sign in …
> SPCR-320 Change aria label for PortField combobox

- src/components/Voyage/VoyageFormValidation.js
- src/components/Voyage/__tests__/VoyageFormValidation.test.js
Currently when a user inputs a departure date in the past, the error reads 'You must enter a departure **time** in the future'. For consistency, this should actually read 'You must enter a departure **date** in the future'. 
Similarly, on the arrival page when a user enters an arrival date in the past the error reads 'You must enter an arrival **time** after your departure' but should read 'You must enter an arrival **date** after your departure'
- Click on a draft voyage plan
- Click to change departure details
- Delete the date and click 'Save and continue'
- The date input error should read 'date' not 'time'
- Enter todays date
- Put a time in the past and click 'Save and continue'
- The error on the time input should still read 'time'
- Repeat with the arrival details
\* Required …
> SPCR-349 Fix departure and arrival error messages

- src/components/User/EditAccount.jsx
- src/components/User/__tests__/EditAccount.test.jsx
> When using the JAWS screen reader and is editing their account information, the screen reader reads that the 'Delete this account button' is a link, not a button.
> 
> The Save button is read out correctly.
The 'Delete this account' button was coded as a link, this has now been changed to a button which has fixed the screen reader issue
- Sign in and go to edit account page
- Use a screenreader and go to the 'delete this account' button
- You should hear the button be described as a button and not a link  
\* Required
> SPCR-359 Change delete account link to button

- src/components/Voyage/FormResponsiblePerson.jsx
> While the user is inputting the skipper's details to the new voyage plan, the JAWS screen reader does not read out the Contact telephone number label for the field. Therefore, the user may be unsure as to what details are required for this field.
Turns out that all of the text input fields weren't labelled properly, so all of them have been fixed for the skipper details page.
\* Required
> SPCR-325 Add correct labelling for edit texts in FormResponsiblePerson

- src/components/Header.jsx
- src/components/Nav.jsx
Fixed a bug where the wrong nav element would be highlighted when signing in from `/account`, `/people`, or `/pleasure-craft` urls. 
- `npm start`
- Go to http://localhost:8080/account
- Sign in
- You should be taken to the voyage plans page
- The people element on the nav bar should *not* be highlighted
- Repeat the steps above with http://localhost:8080/people and http://localhost:8080/pleasure-crafts
\* Required
> SPCR-363 Fix nav highlighting bug

- src/assets/main.scss
Fixed a console warning regarding a stylesheet that was previously not included in the service.
- Sign in
- Open the developer console
- Create a new voyage plan
- Go to the departure form
- You should not see an error relating to `@reach/combobox/styles.css` not being included
- Go the the arrival form
- You should not see an error relating to `@reach/combobox/styles.css` not being included
\* Required
> SPCR-329 Fix console warning about @reach/combobox styles

- src/components/People/FormPerson.jsx
- src/components/Voyage/FormArrival.jsx
- src/components/Voyage/FormDeparture.jsx
- src/components/Voyage/FormVoyagePeopleManifest.jsx
Aria-describedby is looking for a corresponding id but these are missing. Add hint ids to the divs containing hint text and remove unnecessary aria hints where hint text is not displayed.
- Go to person tab
- Click on save a person
- open AXE tools in devtools (needs chrome plugin)
- Run scan
- > There should be no errors mentioning that ARIA attributes must conform to valid values - (there may be other errors that will be resolved in other tickets)
- Repeat with voyage plan departure form (page 1), arrival form (page 2) and people manifest (page 5)
\* Required
> 1.2.0 SPCR-342 Add hint ids and remove unnecessary aria attributes

- src/components/People/FormPerson.jsx
- src/components/PortField.jsx
- src/components/Vessel/FormVessel.jsx
- src/components/Voyage/FormResponsiblePerson.jsx
- src/components/Voyage/PeopleTable.jsx
Currently, there are no ids on the inputs which means that the labels are not linked. Id attributes need to be added to any inputs that do not have an id, so that the htmlFor labels link to the inputs. 
- Go to person tab
- Click on save a person
- Open AXE tools in devtools (needs chrome plugin)
- Run scan
There should be no errors mentioning that form elements must have labels - (there may be other errors that will be resolved in other tickets)
Repeat with **save a pleasure craft form**, voyage plan **departure and arrival (pages 1 &2 )**, and **people manifest (pages 4 & 5)**
\* Required
> 1.2.0 SPCR-335 - Add id attribute to inputs

- src/components-v2/ErrorSummary.jsx
- src/pages/people/PersonForm.jsx
Move the error summary object into its own component, rather than have it repeated for each form in the application. Implement a method that scrolls to label but focuses on the correct input so the user can start inputing the information immediately. 
Add this component to the people form and refactor some code.
- Go to the people tab
- Click the continue button
- All the fields should error
- Click the links in the error summary
- It should scroll to the label and focus on the input
- Fill out the info and continue to the second page
- Click save and all fields should error and the links should work the same as page 1
---
> SPCR-303 Move error summary to its own component

- src/components/CountryField.jsx
- src/components/CountryNationalityField.jsx
- src/constants/ApiConstants.js
> Dev requirements
>- a reusable component
>- can search on 3+ letters 
>- returns search results that match country name
>- returns search results that match country ISO code
>- uses the /nationalities endpoint
>  
> AC
> Given I am interacting with a country/nationality field
> When I have typed at least 3 letters
> I am shown a list of countries names or ISO codes that contain those letters
Created a new country field component that meets these requirements.
- Import CountryField into `DepartureForm.jsx` and create a country component somewhere in the file for testing purposes (discard these changes later)
- `npm start` and navigate to the departure form
- Type one or two letters into the country field
- You should get no results
- Type 3 or more letters
- Results should appear
- …
> SPCR-355 Create country component

- src/components/User/EditAccount.jsx
> There is a bug currently where a user can type an invalid phone number into the Edit Account page and it will successfully save without throwing an error.
The validation has been successfully implemented before, so this needs to be investigated and fixed.
This telephone number validation issue in the Edit Account page has now been fixed.
- Sign in
- Go to Edit Account
- Type in an invalid phone number
- Click save and continue
- You should get an error
- Type in a valid phone number
- Click save and continue
- You should be redirected to the account page
---
> SPCR-380 Fix telephone validation issue in EditAccount

- src/components/Nav.jsx
- src/components/PortField.jsx
- src/components/Voyage/__tests__/FormArrival.test.jsx
- src/components/Voyage/__tests__/FormDeparture.test.jsx
- src/components/__tests__/PortField.test.jsx
> Unit testing for the autocomplete component needs to be implemented, and we should investigate the best way to go about doing this.
Uncommented PortField tests and refactored them into passing.
- `npm test`
- `npm run lint`
- Should be presented with no errors (1 warning which is unrelated to the scope of this ticket)
- Should also successfully compile and run with 'npm start`
- Check through code changes
- Certain tests were deleted as we cannot mock an onSelect action for the combobox. These test cases will be covered by the end to end tests
---
> SPCR-304 Refactor autocomplete tests

- src/components/Main.jsx
- src/components/Vessel/VesselTable.jsx
- src/pages/pleasureCrafts/PleasureCraftForm.jsx
- src/pages/pleasureCrafts/__tests__/PleasureCraftForm.test.jsx
Update pleasure craft form to handle edit and delete cases
- go to /pleasure-crafts
- save a new pleasure craft, ensuring you choose `motorboat`, `no - country of registration`, `no - callsign`
- click the pc you created
- > you should be taken to the pc form with the fields prefilled
- > the 'other' field for pc type should be hidden
- select `other` for pc type
- continue
- > you should see the page 2 fields prefilled
- > you should not see the country of registration or call sign text input fields
- change country of registration to `yes`
- change call sign to `yes`
- save
- > you should be returned to the list of pleasure crafts
- click the pc you just edited
- > you should be taken to page 1 with fields pre-filled, including the other text field
- check type to motorboat
- click …
> SPCR-257 Edit pleasure craft

- src/pages/pleasureCrafts/PleasureCraftForm.jsx
Update the new pleasure craft form to use the ErrorSummary component
- Go to the pleasure craft tab
- Click the continue button
- All the fields should error
- Click the links in the error summary
- It should scroll to the label and focus on the input
- Fill out the info and continue to the second page
- Click save and all fields should error and the links should work the same as page 1
Some radio ids needed to be changed so they could be focused when clicking on the error link
---
> SPCR-381 Implement the ErrorSummary into the pleasure craft form
